name: greek-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask=3.0.2
  - requests=2.31.0
  - python-dotenv=1.0.1
  - pip=23.3.1
  - httpx=0.24.1
  - pip:
    - anthropic==0.3.11
    - ratelimit==2.2.1
    - streamlit>=1.11.0
    - audio-recorder-streamlit>=0.0.8
    - protobuf>=3.20.3
    - urllib3>=1.26.20 